version: "3"
services:
  chrome:
    image: selenium/standalone-chrome-debug:3
    restart: always
    ports:
      - 4444:4444
      - 15900:5900
    volumes:
      - /dev/shm:/dev/shm
  app:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      CHROME_CONTAINER_URL: http://chrome:4444/wd/hub
    tty: true
